window.SALES_TL_SCENARIOS = [
  {
    id: "conversation-with-parents",
    title: "Conversation with parents",
    video: "assets/videos/When_do_I_need_to_make_a_decision.mp4",
    videoTranscript: [
      "It's just kind of where it works for you guys, really.",
      "When do we have to make a decision by?",
      "Well, obviously the quicker the better, but really,",
      "realistically, it's one of you guys are comfortable.",
      "I mean, we're holding Ryan's position now.",
      "We're not going to give that away yet.",
      "Like, there's no reason.",
      "So you guys have got some time if you want to think about it.",
      "But I can definitely get you enrolled now if you want.",
      "And that way we can set up the three things that we do",
      "to get everything set up is booking in a welcome call,",
      "which really is just Ryan getting a sense of.",
      "He has the log in details.",
      "He has how to book in calls.",
      "We're going to, on that call is when he'll book in his weekly Zoom call.",
    ].join("\n"),
    prompt:
      "What are your thoughts on this interaction? If you had to give one or two things that could improve, what would you suggest?",
    danResponse: [
      "Issues",
      "YES - \"The quicker the better\"",
      "HALF - Laughing - it's serious",
      "YES - \"Whenever you guys are comfortable\"",
      "YES - \"I'm holding his position... I can get you enrolled now if you want?\"",
      "YES - Closing steps - premature",
      "",
      "Better",
      "Tonight we discussed Jonny's challenges, including leaving things to the last minute and improving maths.",
      "He seems committed to getting better marks; he said it was a 9/10 to improve.",
      "It does feel like it is a good fit.",
      "Is it a priority for you to deal with these challenges and see an improvement?",
    ].join("\n"),
  },
  {
    id: "close-and-walkout",
    title: "Close & Walkout",
    video: "assets/videos/Do_you_want_to_move_forward.mp4",
    videoTranscript: [
      "Well, parents, how are you guys feeling about everything?",
      "Do you want to move forward?",
      "I don't think I can talk about it first.",
      "I think let's talk about it.",
      "Yeah.",
      "Yeah. All right. No worries.",
      "I've just got a quick.",
      "Of course.",
      "You know, actually, I've already got my eyes for you.",
      "What I might do is I just I'll throw a link.",
      "I think.",
      "Chat.",
      "Let me just.",
      "Let me know when this comes through and if you can see it.",
      "Yep.",
      "There you go. Once you get that open, let me know.",
      "Okay.",
      "It's just up here.",
      "Just go to the chat room.",
      "There.",
      "Yeah.",
      "You see Ryan's all over it.",
      "See.",
      "So that's just some reviews from people who have been a part of the program.",
      "What I've got to do is I've got to jump off quickly and just have a quick chat to a colleague.",
      "So I might just leave you guys to have a quick chat.",
      "I'll be back in about five minutes.",
      "And yeah, you guys.",
      "See if any questions come up.",
      "All right.",
      "All right.",
      "All right.",
    ].join("\n"),
    prompt:
      "What are your thoughts on this interaction? If you had to give one or two things that could improve, what would you suggest?",
    danResponse: [
      "Issues",
      "NO - \"How are you feeling about everything... do you want to move forward?\"",
      "NO - Walk out - no 99%",
      "",
      "Better",
      "Close with the student: Are you happy to make one small change? How do you feel about the program?",
      "Close with the parents: Mum & Dad - all good?",
      "Walkout line: \"I'm happy with whatever you want to do but just so you know...\"",
    ].join("\n"),
  },
  {
    id: "final-part-with-parents",
    title: "Final part with parents",
    video: "assets/videos/Any_other_questions.mp4",
    videoTranscript: [
      "Any other questions I can answer for you while I've got you all right and you",
      "happy with everything I'm happy with what I'm heard yeah great all right well",
      "in that case why don't we bring Ryan back we'll see what he's been writing down",
    ].join("\n"),
    prompt:
      "What are your thoughts on this interaction? If you had to give one or two things that could improve, what would you suggest?",
    danResponse: [
      "Issue: Pink Elephant",
      "No - \"Any other questions?\"",
      "It creates uncertainty.",
    ].join("\n"),
  },
  {
    id: "closing-scenario",
    title: "Closing scenario",
    video: "assets/videos/Kane_-_think_about_it_1.mp4",
    videoTranscript: [
      "But yeah, does that all sound good to you?",
      "It's something we can absolutely discuss, yeah.",
      "Yeah, perfect.",
      "Yeah.",
      "All right.",
      "Well, essentially, what needs to happen from here is that one, two, I'm enrol Patrick into the program.",
      "The first thing we do is we book in a welcome court.",
      "Yeah.",
      "So the foot, it's not a coaching session.",
      "It is just to set you up with passwords and, you know, from there, you'll be able to book after that.",
      "Yeah.",
      "Number two is we process the payment.",
      "And then number three is that we send out all that information, a copy of everything to you as well.",
      "Yeah.",
      "Okay.",
      "So did you want to proceed through with that?",
      "Well, we're going to have to discuss it as a family because it is a pretty big financial commitment.",
      "I absolutely consider benefits, right?",
      "But we're going to need to talk about three of us.",
      "Yeah.",
      "Yeah, to see whether it's something that we can afford and whether.",
      "And we kept to.",
      "Yeah.",
      "Yeah, that's just completely understandable.",
      "All right.",
      "Well, what we'll do now is Patrick, let me know what you've written down.",
      "All right.",
      "Number one was preventing distractions.",
      "Number two.",
    ].join("\n"),
    prompt:
      "What are your thoughts on this interaction? If you had to give one or two things that could improve, what would you suggest?",
    danResponse: [
      "Client says: \"It's something that we can absolutely discuss\"",
      "Translation: I'm not sure. You still need to present the solution in a way that works for me.",
      "",
      "Consultant reply: Well what needs to happen from here is if you want to enrol we book in a welcome call.",
      "Translation: I know you're not sure but here are the details of signing up.",
      "",
      "The problem",
      "If someone is unsure of signing up, you don't provide the details of signing up. You first must get conceptual agreement to go ahead, then you get into the details.",
      "The real problem here is that the father is ironing in the background. The consultant needed to get him into the session, and not proceed until he was at the computer, or reschedule if necessary.",
    ].join("\n"),
  },
];
